// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IncrementSequenceDemos.Models
{
    public partial class Customers
    {
        public Customers()
        {
            CustomerSequence = new HashSet<CustomerSequence>();
            Orders = new HashSet<Orders>();
        }

        public int CustomerIdentifier { get; set; }
        public string CompanyName { get; set; }
        public string ContactName { get; set; }
        public string ContactTitle { get; set; }
        public string City { get; set; }
        public string PostalCode { get; set; }
        public string Country { get; set; }

        public virtual ICollection<CustomerSequence> CustomerSequence { get; set; }
        public virtual ICollection<Orders> Orders { get; set; }
    }
}