// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IncrementSequenceDemos.Models
{
    public partial class Example1
    {
        public int Id { get; set; }
        public string InvoiceNumber { get; set; }
    }
}